name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Change directory to where `gradlew` is located
      - name: Change directory to project root
        run: cd Smartspend/Smartspend

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x Smartspend/Smartspend/gradlew

      - name: Build with Gradle
        run: Smartspend/Smartspend/gradlew build

      - name: Run Unit Tests
        run: Smartspend/Smartspend/gradlew test

      - name: Run Instrumentation Tests
        run: Smartspend/Smartspend/gradlew connectedAndroidTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Smartspend/Smartspend/app/build/reports/tests/testDebugUnitTest/
