name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        working-directory: Smartspend
        run: chmod +x ./gradlew

      # Build with Gradle
      - name: Build with Gradle
        working-directory: Smartspend
        run: ./gradlew build

      # Run Unit Tests
      - name: Run Unit Tests
        working-directory: Smartspend
        run: ./gradlew test

      # Run Instrumentation Tests
      - name: Run Instrumentation Tests
        working-directory: Smartspend
        run: ./gradlew connectedAndroidTest

      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Smartspend/app/build/reports/tests/testDebugUnitTest/
