name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Ensure gradlew has execute permissions
      - name: Grant execute permission for gradlew
        run: chmod +x ${{ github.workspace }}/gradlew

      - name: Build with Gradle
        run: ${{ github.workspace }}/gradlew build

      - name: Run Unit Tests
        run: ${{ github.workspace }}/gradlew test

      - name: Run Instrumentation Tests
        run: ${{ github.workspace }}/gradlew connectedAndroidTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/
